GET http://localhost:3002/note-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNTBjOThiYzM5ZTM0YzQ4MTA2ZTExNiIsImNvbmZpcm1BY2NvdW50Ijp0cnVlLCJlbWFpbCI6ImZlci5sYy5kZXZlbG9wZXJAZ21haWwuY29tIiwidG9rZW5Db25maXJtIjpudWxsLCJ1c2VyTmFtZSI6ImZlcmxjIiwiY3JlYXRlZEF0IjoiMjAyMi0xMC0yMFQwNDowNzozOS44MDBaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0yMFQwNDowNzozOS44MDBaIn0sImp0aSI6IlJhWnVMbEJ5TDgiLCJpYXQiOjE2NjYyNTk1OTYsImV4cCI6MTY2NjM0NTk5Nn0.ZnXd4JfirHyx5Pqxft0YZKNIRYnslJj5ALmi1b062aQ